name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  waka-readme-simple:
    name: 📊 WakaTime Minimal Stats
    runs-on: ubuntu-latest
    steps:
      - name: Update README with WakaTime Stats (Athul)
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          REPOSITORY: victorvaladez1/victorvaladez1
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          BLOCKS: "░▒▓█"
          COMMIT_MESSAGE: "📊 Update basic WakaTime stats"
